# Generated by Django 3.1.3 on 2023-01-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pd_content',
            field=models.TextField(default=''),
        ),
    ]
